server:
  port: 2000

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8000/eureka}

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoreSecurityHeaders: false
  prefix: /api/v1/
  routes:
    demo:
      path: /demo/**
      serviceId: demo-service

